### ISSUE TITLE
Convert to Hugo

### ISSUE THREAD

**Issue by liamcurry** [armstrhb/DesignPatterns#2]
Converting to a static site generator like [Hugo](http://gohugo.io/) will make creating new posts, RSS feeds, sitemaps, etc. a lot easier.

I've done some work on converting things over on [the `hugo` branch](https://github.com/liamcurry/DesignPatterns/tree/hugo).
## TODO
- [x] Convert existing posts to Markdown
- [x] Split up templates into partials
- [x] [Use server-side syntax highlighting](http://gohugo.io/extras/highlighting/)
- [x] Homepage
- [ ] Patterns index page (partially complete)
- [ ] About page (needs copy)
- [ ] [Add RSS feed](http://gohugo.io/templates/rss/) (partially complete)
- [ ] [Add sitemap](http://gohugo.io/templates/sitemap/) (partially complete)
- [ ] [Style 404 page](http://gohugo.io/templates/404/)
- [ ] Concat/minify Javascript/CSS
- [ ] Add Makefile or Gulpfile to automate routine tasks
